project:
  type: website
  output-dir: docs

website:
  title: "Dr Harriet B. Drage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
    right:
      - icon: github
        href: https://github.com/harrietdrage
        target: _blank
      #- href: file/path/to/myCV.pdf # providing a relative file path to a pdf will open up a browser-based pdf viewer when clicked
       # text: CV
        #target: _blank # opens link (or page) in a new browser tab
  page-footer: 
    background: light # or `dark'
    left: Copyright 2024, Harriet B. Drage
    right:
      - icon: r-project
      - icon: github

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

