---
image: /IMG_3987.HEIC
about: 
  template: trestles
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/harriet-drage-48444a131/
    - text: "{{< fa brands orcid >}} ORCiD"
      href: https://orcid.org/0000-0002-0759-5970
    - icon: cloud
      text: Web of Science
      href: https://www.webofscience.com/wos/author/record/AAC-7414-2022
    - icon: twitter
      text: BlueSky
      href: https://bsky.app/profile/harriedrage.bsky.social
    - icon: github
      text: github
      href: https://github.com/harrietdrage
    - text: "{{< fa brands researchgate >}} ResearchGate"
      href: https://www.researchgate.net/profile/Harriet-Drage-2
---

<h2>Value-driven leader, open science advocate, fan of fossils.</h2>

I am an Assistant Professor at the University of Geneva, working on the palaeobiology and palaeoecology of arthropods in deep time. To do so, I employ sophisticated computational analytical methods, statistics, and fluid dynamics techniques, using big data. I am an advocate of open-access publishing and data, and enjoy dabbling in web design.

I am dedicated to improving publishing, conditions in academia, and inclusivity. I am Co-Founder and Managing Editor of <i>Open Palaeontology</i> (ISSN:), and Newsletter Editor and Charity Trustee for <i>The Palaeontological Association</i>.

I worked previously as a Commissioning Editor for science in secondary education (age 11--18) for Oxford University Press. In my spare time, I enjoy climbing, hiking, weightlifting, video games, and sewing.

<h3>Education</h3>

<h5>University of Oxford \| PhD in Environmental Research</h5>

\| Oct 2014 -- Dec 2018

<h5>University College London \| MSci in Palaeobiology</h5>

\| Oct 2010 -- Oct 2014

<h3>Employment</h3>

<h5>University of Geneva \| Assistant Professor, ERC Starting Grant</h5>

\| Sep 2026 -- present

<h5>University of Lausanne \| Postdoctoral Researcher</h5>

\| Sep 2021 -- Jun 2026

<h5>University Oxford Press \| Commissioning Editor, Secondary Science Education</h5>

\| Jan 2021 -- Oct 2021

<h5>University Oxford Press \| Development Editor, Secondary Science Education</h5>

\| Sep 2019 -- Jan 2021

<h5>University Oxford Press \| Editor, Secondary Science Education</h5>

\| Jan 2019 -- Sep 2019
